name: Test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 17]

    name: Node ${{ matrix.node }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Ensure apt-get is updated
        run: sudo apt-get update

      - name: Install Canvas and XML dependencies
        run: sudo apt-get install -y libxml2-utils

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test:no-lint

      - name: Lint
        run: yarn lint
